hillcourt/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

# Template urls!
app_name = 'basic_app'

urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^user_login/$', views.user_login, name='user_login'),
    url(r'^home/', views.home, name='home'),
    url(r'^overview/', views.overview, name='overview'),
    url(r'^location/', views.location, name='location'),
    url(r'^amenities/', views.amenities, name='amenities'),
    url(r'^specification/', views.specification, name='specification'),
    url(r'^about_the_partners/', views.about_the_partners, name='about_the_partners'),
]

hillcourt/hillcourt/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from basic_app import views

urlpatterns = [
    url(r'^$',views.index, name='index'),
    url(r'^basic_app/', include('basic_app.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^special/$', views.special, name='special'),
    path('admin/', admin.site.urls),
]

hillcourt/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.DO_NOTHING)

    profile_pic = models.ImageField(upload_to='profile_pic', blank=True)

    def __str__(self):
        return self.user.username

hillcourt/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('profile_pic',)

hillcourt/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm,UserProfileInfoForm

from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth import authenticate,login,logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request, 'basic_app/index.html')

@login_required
def special(request):
    return HttpResponse("You are logged in!")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user - user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()
            registered = True

        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'basic_app/registration.html', {'user_form':user_form, 'profile_form':profile_form, 'registered':registered})


def user_login(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("Account not active")
        else:
            print("Someone tried to login and failed")
            print("Username: {} and password: {}".format(username,password))
            return HttpResponse("invalid login details supplied")
    else:
        return render(request, 'basic_app/login.html', {})

def home(request):
    return render(request,'basic_app/home.html')

def overview(request):
    return render(request,'basic_app/overview.html')

def location(request):
    return render(request,'basic_app/location.html')

def amenities(request):
    return render(request,'basic_app/amenities.html')

def specification(request):
    return render(request,'basic_app/specification.html')

def about_the_partners(request):
    return render(request,'basic_app/about_the_partners.html')

hillcourt/templates/basic_app/about_the_partners.html
{% extends "basic_app/base.html" %}
{% load static %}
{% block body-block %}
  <div class="div16">
    <p class="about">ABOUT THE PARTNERS</p>
    <h1 class="best">Elevated by Nothing But The Best</h1>
    <p class="para18">
      A leading real estate player in India, Conscient has so far delivered over 11,000 homes across Delhi-NCR, Dehradun & Goa in the last 4 decades. Based in USA, Hines is a privately-owned global real estate investment, development and management firm, founded in 1957, with a presence in 214 cities across 24 countries and $120.6 billion of assets under management.
      <br>
      <br>
      Tata Projects, renowned as India’s fastest growing and most admired infrastructure company, has rich expertise in executing complex urban construction projects.
      <br>
      <br>
      The two industry stalwarts, Hines and Conscient, with Tata Projects appointed as a construction partner, have together joined hands to create their first residential landmark in India and raise the bar of Gurugram’s lifestyle with Elevate.
    </p>
  </div>

  <div class="div17">

    <div class="div18">
      <p>DEVELOPER</p>
    </div>

    <div class="div21">
      <p class="para19">ACCENT</p>
      <p class="para20">Buidtech Pvt Ltd.</p>
    </div>

    <div class="div19">
      <p>INVESTMENT MANAGER</p>
      <img src="{% static 'images/hines.png' %}" alt="">
    </div>

    <div class="div20">
      <p>INVESTMENT MANAGER</p>
      <img src="{% static 'images/tata.png' %}" alt="">
    </div>
  </div>
{% endblock %}

hillcourt/templates/basic_app/amenities.html
{% extends "basic_app/base.html" %}
{% load static %}
{% block body-block %}
  <div class="div9">
    <img src="{% static 'images/amen.png' %}" alt="">
  </div>

  <div class="div10">
    <p class="para12">AMENITIES</p>
    <h1 class="elevate">Upgrade To A Peaceful Lifestyle</h1>
    <p class="para13">
      Luxury is what luxury can do for you. Our premium amenities lets you enjoy the opulence while appreciating their functional importance in our grand design.
    </p>
  </div>

  <div class="div11">
    <p>Explore Amenities</p>
  </div>

{% endblock %}

hillcourt/templates/basic_app/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>HillCourt Residency</title>

    <link rel="stylesheet" href="{% static "css/hill.css" %}">

  </head>
  <body>

    <nav class ='navbar'>
      <div class="div1">
        <img src="static/images/HillCourt.png" alt="">
        <ul class="">
          
          <li><a href="{% url 'basic_app:home' %}">HOME</a></li>
          <li><a href="{% url 'basic_app:overview' %}">OVERVIEW</a></li>
          <li><a href="{% url 'basic_app:location' %}">LOCATION</a></li>
          <li><a href="{% url 'basic_app:amenities' %}">AMENITIES</a></li>
          <li><a href="{% url 'basic_app:specification' %}">SPECIFICATIONS</a></li>
          <li><a href="{% url 'basic_app:about_the_partners' %}">ABOUT THE PARTNERS</a></li>
          <li><a href="{% url 'basic_app:register' %}">REGISTER</a></li>

          {% if user.is_authenticated %}
            <li><a class="" href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="" href="{% url 'basic_app:user_login' %}">Login</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>


    <div>
      {% block body-block %}
      {% endblock %}
    </div>
  </body>
</html>

hillcourt/templates/basic_app/home.html
{% extends "basic_app/base.html" %}
{% load static %}
{% block body-block %}

<div class="front">
  <img src="{% static 'images/home.png' %}" alt="">

  <div class="front1">
    <p class="para1">WORLD-CLASS 3 & 4 BED RESIDENCES FROM RS. 2.42 CR.*</p>
    <p class="para2">BHivadi Haryana</p>
    <p class="para3">View Location</p>

      <div class="front2">
        <p class="para4">Know More</p>
      </div>

      <div class="front3">
        <p class="para5">DEVELOPER</p>
      </div>

      <div class="front4">
        <p class="para6">ACCENT</p>
        <p class="para7">Buidtech Pvt Ltd.</p>
      </div>

    <p class="para8">HRERA 19 OF 2019. A PROJECT BY HERITAGE MAX REALTECH PVT. LTD.</p>
  </div>
</div>

{% endblock %}

hillcourt/templates/basic_app/index.html
{% extends "basic_app/base.html" %}
{% block body-block %}
  <div class="jumbotron">
    <h1></h1>
  </div>
{% endblock %}

hillcourt/templates/basic_app/location.html
{% extends "basic_app/base.html" %}
{% load static %}
{% block body-block %}
  <div class="div2">
    <p class="loca">LOCATION</p>
    <h1 class="location">Strategic Location That Uplifts You</h1>
    <p class="para11">
      Located off the Golf Course Extension Road, sans traffic and dust, with direct connectivity from both Delhi and Gurugram, Elevate enjoys lush views of the Aravallis in a premium upscale neighbourhood.
    </p>
  </div>

  <div class="div3">
    <p><img src="{% static 'images/maplogo.png' %}" alt=""> VIEW GOOGLE MAP</p>
  </div>

  <div class="div4">
    <img src="{% static 'images/map.png' %}" alt="">
  </div>

  <div class="div5">
    <img src="{% static 'images/school.png' %}" alt="">
    <p>SCHOOLS</p>
    <ul>
      <li>Heritage School - 5 mins</li>
      <li>DPS International School - 5 min</li>
      <li>Heritage School - 5 mins</li>
    </ul>
  </div>

  <div class="div6">
    <img src="{% static 'images/connectivity.png' %}" alt="">
    <p>CONNECTIVITY</p>
    <ul>
      <li>Heritage School - 5 mins</li>
      <li>DPS International School - 5 min</li>
      <li>Heritage School - 5 mins</li>
    </ul>
  </div>

  <div class="div7">
    <img src="{% static 'images/office.png' %}" alt="">
    <p>OFFICES</p>
    <ul>
      <li>Heritage School - 5 mins</li>
      <li>DPS International School - 5 min</li>
      <li>Heritage School - 5 mins</li>
    </ul>
  </div>

  <div class="div8">
    <img src="{% static 'images/hospital.png' %}" alt="">
    <p>MEDICAL FACILITIES</p>
    <ul>
      <li>Heritage School - 5 mins</li>
      <li>DPS International School - 5 min</li>
      <li>Heritage School - 5 mins</li>
    </ul>
  </div>
{% endblock %}

hillcourt/templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
{% block body-block %}
  <div class="jumbotron">
    <h1>Please Login</h1>

    <form action="{% url 'basic_app:user_login' %}" method="post">
      {% csrf_token %}
      <label for="username">Username:</label>
      <input type="text" name="username" placeholder="Enter Username">

      <label for="password">Password:</label>
      <input type="password" name="password">

      <input type="submit" name="" value="Login">
    </form>
  </div>
{% endblock %}

hillcourt/templates/basic_app/overview.html
{% extends "basic_app/base.html" %}
{% load static %}
{% block body-block %}
    <div class="over1">
      <p class="over">OVERVIEW</p>
      <h1 class="build">Built By The Best</h1>
      <p class="para9">
        Elevate is the brainchild of two industry stalwarts - pan-India developer, Conscient and global giant, Hines. Teaming up with this formidable duo, Tata Projects now joins them as a construction partner. This oasis of serenity has been perfected with masterful strokes from Ricardo, an internationally renowned Spanish architecture firm.<br>
        <br>
        <br>
        These landmark residences bring to you an elevated living experience with a balance of world-class architecture, engineering excellence and construction expertise, delivered only by the best in the industry.
      </p>
    </div>

    <div class="over2">
      <img src="{% static 'images/overview1.png' %}" alt="" class="img1">
    </div>

    <div class="over3">
      <img src="{% static 'images/overview2.png' %}" alt="" class="img2">

    </div>
    <div class="over4">
      <h2 class="head">FINEST FOR FINESTS</h2>
      <p class="para10">
        Elevate is the brainchild of two industry stalwarts - pan-India developer, Conscient and global giant, Hines. Teaming up with this formidable duo, Tata Projects now joins them as a construction part
      </p>
    </div>
{% endblock %}

hillcourt/templates/basic_app/registration.html
{% extends "basic_app/base.html" %}

  {% block body-block %}
  <div class="">
    {% if registered %}
      <h1>Thank you for registration!</h1>

    {% else %}
      <h1>Register Here!</h1>
      <h3>Fill Out The Form:</h3>

      <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p}}
        <input type="submit" name="" value="Register">
      </form>

    {% endif %}
  </div>
  {% endblock %}

hillcourt/templates/basic_app/specification.html
{% extends "basic_app/base.html" %}
{% load static %}
{% block body-block %}
  <div class="div12">
    <p class="para14">Specifications</p>
    <h1 class="feel">Feel Inspired By Aesthetic Interiors</h1>
  </div>

  <div class="div13">
    <p class="para15">
      Located off the Golf Course Extension Road, sans traffic and dust, with direct connectivity from both Delhi and Gurugram, Elevate enjoys lush views of the Aravallis in a premium upscale neighbourhood.
    </p>
  </div>

  <div class="div14">
    <img src="{% static 'images/spes.png' %}" alt="">
  </div>

  <div class="div15">
    <p class="para16">Master bed room / dress room</p>
    <p class="para17">
      1.Floor <br>Lorem ipsum dolor sit amet, consectetur adipiscing elit <br><br>
      2.Wall <br>Lorem ipsum dolor sit amet, consectetur adipiscing elit <br><br>
      3.Cieling <br>Lorem ipsum dolor sit amet, consectetur adipiscing elit <br><br>
    </p>
  </div>


{% endblock %}